- name: configure backend server
  become: yes
  hosts: backend
  vars:
     login_host: db.expense.fun
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf: #dnf only works for Redhat family (homogeneous) 
       name: "{{ item }}"
       state: installed
    loop:
    - nodejs
    - mysql

  - name: create expense user
    ansible.builtin.user:
        name: expense
